# Generated by Django 3.1.3 on 2021-05-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
