# Generated by Django 3.1.3 on 2021-05-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authaccounts', '0002_auto_20210507_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
